services:

  - type: keyvalue
    name: alpha-ai-redis
    plan: free
    region: oregon
    ipAllowList: []

  - type: web
    name: alpha-ai-backend
    runtime: docker
    plan: free
    region: oregon

    dockerfilePath: ./backend/Dockerfile
    dockerContext: .

    healthCheckPath: /

    envVars:

      - key: PORT
        value: "10000"

      # Internal services
      - key: AUTH_SERVICE
        value: http://127.0.0.1:8001

      - key: CHAT_SERVICE
        value: http://127.0.0.1:8002

      - key: AGENT_SERVICE
        value: http://127.0.0.1:8003

      - key: BILLING_SERVICE
        value: http://127.0.0.1:8004

      # Redis
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alpha-ai-redis
          property: connectionString

      # MongoDB
      - key: MONGODB_URI
        sync: false

      # Firebase
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false

      # Email
      - key: SMTP_URL
        sync: false

      # AI
      - key: GROQ_API_KEY
        sync: false

      - key: GOOGLE_API_KEY
        sync: false

      - key: OPENROUTER_API_KEY
        sync: false

      - key: OPENAI_API_KEY
        sync: false

      - key: TAVILY_API_KEY
        sync: false

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      # RAG
      - key: QDRANT_URL
        sync: false

      - key: QDRANT_API_KEY
        sync: false

      # Razorpay
      - key: RAZORPAY_KEY_ID
        sync: false

      - key: RAZORPAY_KEY_SECRET
        sync: false

      # Frontend
      - key: FRONTEND_URL
        sync: false