import { uploadBuffer } from "../config/cloudinary.js";
import { getModel } from "../config/llmModels.js";
import { deductCredits } from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentLimit.js";
import generatePdf from "../utils/generatePDF.js";

export const resumeAgent = async (state) => {
  try {
    await checkAgentLimit(state.userId, "resume");
    const llm = await getModel("resume", state.plan);

    const systemPrompt = `
You are Alpha AI's elite Executive Resume Architect & ATS Optimization Specialist.
Your task is to craft an exceptional, high-impact, ATS-compliant professional resume based on the user's details.

Return ONLY valid JSON matching this exact structure:
{
  "title": "Candidate Name - Professional Title",
  "subtitle": "email@example.com | +91 9876543210 | City, Country | LinkedIn | GitHub",
  "sections": [
    {
      "heading": "Professional Summary",
      "points": [
        "Concise, metric-driven summary highlighting key strengths, years of experience, and core competencies."
      ]
    },
    {
      "heading": "Core Skills & Competencies",
      "points": [
        "Technical Skills: List key languages, frameworks, tools, and platforms relevant to the target role.",
        "Methodologies & Domains: Agile, CI/CD, System Design, Cloud Architecture, Leadership."
      ]
    },
    {
      "heading": "Professional Experience",
      "points": [
        "Job Title | Company Name | Start Year - End Year / Present",
        "• Spearheaded [Initiative/Project], driving a X% increase in performance/revenue using [Tech/Methodology].",
        "• Architected and deployed scalable solutions that reduced downtime/latency by Y%.",
        "• Collaborated across cross-functional engineering and product teams to deliver milestones on schedule."
      ]
    },
    {
      "heading": "Key Projects",
      "points": [
        "Project Name: Developed a full-stack solution featuring [Tech Stack], handling [scale/users] with high reliability.",
        "Key Feature / Impact: Implemented real-time streaming, OAuth2 security, and automated CI/CD pipeline."
      ]
    },
    {
      "heading": "Education & Certifications",
      "points": [
        "Degree Name | Institution / University | Graduation Year",
        "Relevant Certifications: AWS Certified / Google Cloud Professional / Meta Certified."
      ]
    }
  ]
}

STRICT GUIDELINES:
1. ATS Optimization: Use standard section headings ("Professional Summary", "Core Skills & Competencies", "Professional Experience", "Key Projects", "Education & Certifications").
2. Action Verbs & Metrics: Start accomplishment points with strong action verbs (Engineered, Architected, Spearheaded, Accelerated). Quantify impact where appropriate.
3. Structure Consistency: Every section MUST have a "heading" string and a "points" array of strings.
4. Output Integrity: Do not include markdown code fences, asterisks, backticks, or any conversational text outside the JSON object.

User Information / Requirements:
${state.prompt}
`;

    const response = await llm.invoke(systemPrompt);
    const rawContent = Array.isArray(response?.content)
      ? response.content.map((part) => (typeof part === "string" ? part : part?.text || "")).join("")
      : String(response?.content ?? "");

    const jsonText = rawContent
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .replace(/^\s*[*-]\s*/gm, "")
      .trim();

    const jsonStart = jsonText.indexOf("{");
    const jsonEnd = jsonText.lastIndexOf("}");
    const cleanJsonText = jsonStart >= 0 && jsonEnd > jsonStart ? jsonText.slice(jsonStart, jsonEnd + 1) : jsonText;

    let data;
    try {
      data = JSON.parse(cleanJsonText);
    } catch (parseError) {
      // Safe fallback structure if model output had a slight JSON formatting flaw
      data = {
        title: "Professional Resume",
        subtitle: "Generated by Alpha AI",
        sections: [
          {
            heading: "Profile Overview",
            points: [state.prompt.slice(0, 300)]
          }
        ]
      };
    }

    if (!data?.title || !Array.isArray(data?.sections)) {
      throw new Error("Invalid resume payload structure");
    }

    await deductCredits(state.userId, "resume");

    const pdfBuffer = await generatePdf(data);
    const fileName = `resume-${Date.now()}.pdf`;
    const uploaded = await uploadBuffer(pdfBuffer, {
      public_id: fileName,
      resource_type: "raw",
      format: "pdf",
    });

    const downloadUrl = uploaded?.secure_url || "";

    return {
      ...state,
      aiResponse: `✅ **Resume generated successfully.**\n\n📄 **${data.title}**\n\n🔗 [Download Resume (PDF)](${downloadUrl})\n\n*(Download link valid for 24 hours)*`,
    };
  } catch (error) {
    console.error("Resume generation failed:", error?.response?.data || error?.message || error);
    return {
      ...state,
      aiResponse: error?.data?.message || error?.message || "❌ Failed to Generate Resume. Please try again.",
    };
  }
};