import PDFDocument from "pdfkit";

const generatePdf = async (data = {}) => {
    return new Promise((resolve, reject) => {
        const title = String(data?.title || "Alpha AI Document");
        const subtitle = data?.subtitle ? String(data.subtitle) : "";
        const sections = Array.isArray(data?.sections) ? data.sections : [];

        const document = new PDFDocument({
            margin: 50,
            size: "A4",
            info: {
                Author: "Alpha AI",
                Title: title,
                Creator: "Alpha AI"
            }
        });

        const chunks = [];

        document.on("data", chunk => chunks.push(chunk));
        document.on("end", () => resolve(Buffer.concat(chunks)));
        document.on("error", (err) => reject(err));

        document.fontSize(26).text(title, { align: "center" }).fillColor("#111827");

        if (subtitle) {
            document.moveDown(0.5);
            document.fontSize(12).text(subtitle, { align: "center" }).fillColor("#6B7280");
        }

        document.moveDown(2);

        sections.forEach(sec => {
            const heading = sec?.heading ? String(sec.heading) : "Section";
            document.fontSize(18).text(heading).fillColor("#111827");
            document.moveDown(0.5);

            const points = Array.isArray(sec?.points) ? sec.points : [];
            points.forEach((p) => {
                document.fontSize(12).text(`• ${String(p)}`, {
                    lineGap: 5
                }).fillColor("#374151");
            });

            document.moveDown();
        });

        document.moveDown();
        document.fontSize(10).text("Generated by Alpha AI", { align: "center" }).fillColor("#9CA3AF");
        document.end();
    });
};

export default generatePdf